baseURL: '/'
defaultContentLanguage: pt
languageCode: 'pt-br'
disableKinds:
  - 'RSS'
  - 'sitemap'
enableRobotsTXT: false
metaDataFormat: 'yaml'
enableMissingTranslationPlaceholders: true
disableFastRender: true
ignoreFiles: ['\\.tmp$', '\\.tmp\\-browserify']
stepAnalysis: true
templateMetrics: true
pluralizeListTitles: true
preserveTaxonomyNames: true
googleAnalytics: 'UA-90457577-1'
buildFuture: true
FootnoteReturnLinkContents: '↩'
disableHugoGeneratorInject: true
removePathAccents: true
taxonomies:
  role: 'role'
  tag: 'tags'
  category: 'categories'
  author: 'authors'
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
permalinks:
  pages: /:slug/
languages:
  pt:
    contentDir: content/pt
    languageName: 'Português Brasil'
    languageCode: 'pt-br'
    title: 'YouBet! School'
    weight: 1
    params:
      tagline: 'Quer se tornar um Cidadão Global?'
      email: 'contato@youbetschool.com'
      mailchimpList: '#'
      description:
        default: 'Queremos criar um país bilíngue de mente globalizada, impulsionando o intercâmbio'
        twitter: 'Queremos criar um país bilíngue de mente globalizada, impulsionando o intercâmbio'
        facebook: 'Queremos criar um país bilíngue de mente globalizada, impulsionando o intercâmbio'
      shareImages:
        default: 'assets/images/compartilhamento.jpg'
        twitter: 'assets/images/twitter-compartilhamento.jpg'
        facebook: 'assets/images/facebook-compartilhamento.jpg'

    menu:
      main:
        - Name: 'Sobre'
          Pre: ''
          Weight: 1
          Identifier: 'about'
          URL: '/sobre'
        - Name: 'Blog'
          Pre: ''
          Weight: 2
          Identifier: 'blog'
          URL: '/blog'
        - Name: 'Programas'
          Pre: ''
          Weight: 3
          URL: '/programas'
          Identifier: 'programs'
        - Name: 'Ensino Médio'
          Pre: ''
          Weight: 1
          Identifier: 'high-school'
          URL: '/programas/ensino-medio'
          parent: 'programs'
        - Name: 'Futebol'
          Pre: ''
          Weight: 2
          Identifier: 'futebol'
          URL: '/programas/futebol'
          parent: 'programs'
        - Name: 'Intercâmbio de Inverno'
          Pre: ''
          Weight: 3
          Identifier: 'winter'
          URL: '/programas/intercambio-de-inverno'
          parent: 'programs'
        - Name: 'Intercâmbio de Verão'
          Pre: ''
          Weight: 4
          Identifier: 'summer'
          URL: '/programas/intercambio-de-verao'
          parent: 'programs'
        - Name: 'Todos'
          Pre: ''
          Weight: 5
          Identifier: 'allPrograms'
          URL: '/programas'
          parent: 'programs'
        - Name: 'Parceiros'
          Pre: ''
          Weight: 4
          URL: '/parceiros'
          Identifier: 'partners'
        - Name: 'Contato'
          Pre: ''
          Weight: 5
          Identifier: 'contact'
          URL: '/contato'

  en:
    contentDir: content/en
    languageName: 'English'
    languageCode: 'en'
    title: 'YouBet! Real English'
    weight: 2
    params:
      tagline: 'cultural immersion'
      email: 'contato@youbetschool.com'
      mailchimpList: '#'
      description:
        default: 'We want to create a bilingual country with a global mind, promoting exchange'
        twitter: 'We want to create a bilingual country with a global mind, promoting exchange'
        facebook: 'We want to create a bilingual country with a global mind, promoting exchange'
      shareImages:
        default: 'assets/images/compartilhamento.jpg'
        twitter: 'assets/images/twitter-compartilhamento.jpg'

    menu:
      main:
        - Name: 'About'
          Pre: ''
          Weight: 1
          Identifier: 'about'
          URL: '/en/about'
        - Name: 'Programs'
          Pre: ''
          Weight: 3
          URL: '/en/programs'
          Identifier: 'programs'
        - Name: 'High School'
          Pre: ''
          Weight: 1
          Identifier: 'high-school'
          URL: '/en/programs/ensino-medio'
          parent: 'programs'
        - Name: 'Soccer'
          Pre: ''
          Weight: 2
          Identifier: 'futebol'
          URL: '/en/programs/futebol'
          parent: 'programs'
        - Name: 'Winter Exchange'
          Pre: ''
          Weight: 3
          Identifier: 'winter'
          URL: '/en/programs/intercambio-de-inverno'
          parent: 'programs'
        - Name: 'Summer Exchange'
          Pre: ''
          Weight: 4
          Identifier: 'summer'
          URL: '/en/programs/intercambio-de-verao'
          parent: 'programs'
        - Name: 'All'
          Pre: ''
          Weight: 5
          Identifier: 'allPrograms'
          URL: '/en/programs'
          parent: 'programs'
        - Name: 'Partners'
          Pre: ''
          Weight: 4
          Identifier: 'partners'
          URL: '/en/partners'
        - Name: 'Contact'
          Pre: ''
          Weight: 5
          Identifier: 'contact'
          URL: '/en/contact'

  es:
    contentDir: content/es
    languageName: 'Español (España)'
    languageCode: 'es-es'
    title: 'YouBet! School'
    weight: 3
    params:
      tagline: 'Inmersión cultural'
      email: 'contato@youbetschool.com'
      mailchimpList: '#'
      description:
        default: 'Queremos crear un país bilingüe con una mente global, impulsando el intercambio cultural'
        twitter: 'Queremos crear un país bilingüe con una mente global, impulsando el intercambio cultural'
        facebook: 'Queremos crear un país bilingüe con una mente global, impulsando el intercambio cultural'
      shareImages:
        default: 'assets/images/compartilhamento.jpg'
        twitter: 'assets/images/twitter-compartilhamento.jpg'

    menu:
      main:
        - Name: 'Sobre nosotros'
          Pre: ''
          Weight: 1
          Identifier: 'about'
          URL: '/es/sobre'
        - Name: 'Programas'
          Pre: ''
          Weight: 3
          URL: '/es/programas'
          Identifier: 'programs'
        - Name: 'Bachillerato'
          Pre: ''
          Weight: 1
          Identifier: 'high-school'
          URL: '/es/programas/ensino-medio'
          parent: 'programs'
        - Name: 'Fútbol'
          Pre: ''
          Weight: 2
          Identifier: 'futebol'
          URL: '/es/programas/futebol'
          parent: 'programs'
        - Name: 'Intercambio de invierno'
          Pre: ''
          Weight: 3
          Identifier: 'winter'
          URL: '/es/programas/intercambio-de-inverno'
          parent: 'programs'
        - Name: 'Intercambio de verano'
          Pre: ''
          Weight: 4
          Identifier: 'summer'
          URL: '/es/programas/intercambio-de-verao'
          parent: 'programs'
        - Name: 'Todos'
          Pre: ''
          Weight: 5
          Identifier: 'allPrograms'
          URL: '/es/programas'
          parent: 'programs'
        - Name: 'Socios'
          Pre: ''
          Weight: 4
          Identifier: 'partners'
          URL: '/es/socios'
        - Name: 'Contacto'
          Pre: ''
          Weight: 5
          Identifier: 'contact'
          URL: '/es/contacto'

params:
  googleTag: 'GTM-PXT9Q4L'
  authors:
    - Name: 'Evelyn Perez'
      Weight: 1
    - Name: 'Stephanie Castro'
      Weight: 2
